development:
  host: localhost
  port: 49823
  database: nomad_test

test:
  host: localhost
  port: 49823
  database: nomad_test

# set these environment variables on your prod server
production:
  host: localhost
  port: 27017
  database: nomad